SKIP_STRING = "Press Enter to Skip"
EMPTY_TEXT = "[bright_black]Empty[/bright_black]"
HIDDEN_TEXT = "[bright_magenta]******[/bright_magenta]"
ERROR = "[red]ERROR:[/red]"
RANDOM_PASSWORD_PROMPT = "Press Enter for a random Password"
