SKIP_STRING = "Press Enter to Skip"
EMPTY_TEXT = "[bright_black]Empty[/bright_black]"
HIDDEN_TEXT = "[bright_magenta]******[/bright_magenta]"
ERROR = "[red]ERROR:[/red]"
MASTER_PASSWORD_ERROR = "[red]Master Password is Incorrect[/]"
MASTER_PASSWORD_NOT_FOUND_ERROR = "No master password found"
RANDOM_PASSWORD_PROMPT = "Press Enter for a random Password"
COPIED_TO_CLIPBOARD = "[green]:clipboard: Password copied to clipboard![/green]"
